- src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/I24/serial/setup_beamline/pv_abstract.py
- src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
- tests/I24/serial/extruder/test_extruder_collect.py
- tests/I24/serial/setup_beamline/test_setup_beamline.py
Add a small function to find which detector is in use.
Employing roughly the same logic used in GDA to check the detector and move it to correct positioning. There's probably a better way, but for now it does the job. 
Part of #14
> I24 ssx: determine detector

- src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
Temporarily add a timeout to the data collection in case something goes wrong and it gets stuck. During the last testing there were a few issues that caused the data collection to fail, but the script was not getting out of the while loop and just kept going because conditions on the PVs were not met. It also could not be easily killed from the terminal.
Needs a better solution for the future but this should allow for a slightly safer testing of the deployment. 
Timeout is calculated from the number of images to be collected and the exposure time plus a constant in seconds. Probably overdoing it with the chip, but better be safe since I'm not considering the pump_repeat in it.
> Add a timeout to the data collection

- .github/pages/make_switcher.py
- .github/workflows/code.yml
- .github/workflows/docs.yml
- .github/workflows/linkcheck.yml
- .gitignore
- .pre-commit-config.yaml
- .vscode/extensions.json
- .vscode/settings.json
- docs/conf.py
- docs/developer/how-to/lint.rst
- docs/developer/reference/standards.rst
- pyproject.toml
- src/mx_bluesky/I24/serial/dcid.py
- tests/I24/serial/fixed-target/test_ft_collect.py
Closes #53 . 
Replace isort/flake8 in pre-commits with Ruff.
Also pin builds to 3.11 as p4p doesn't build in 3.12 (stop docs from failing)
> Use ruff as a linter

- src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DetStage.edl
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
- src/mx_bluesky/I24/serial/log.py
- src/mx_bluesky/I24/serial/setup_beamline/setup_detector.py
- tests/I24/serial/fixed_target/test_moveonclick.py
- tests/I24/serial/setup_beamline/test_setup_detector.py
For Viewer/OAVParams issue see #44
> I24 ssx test hotfixes

- pyproject.toml
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
Use the new OAV parameters definition, which has been changed so that the ones inherent to the OAV are now decoupled from the context. 
See also [Dodal#224](https://github.com/DiamondLightSource/dodal/pull/239)
> Use new OAV from dodal for moveonclick

- pyproject.toml
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
- tests/I24/serial/fixed_target/test_moveonclick.py
Set the pmac_string using an ophyd device in moveonclick.
Part of #54 
Needs Dodal [#254](https://github.com/DiamondLightSource/dodal/pull/254)
> Use ophyd device for pmac in moveonclick

- pyproject.toml
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
Needs [Dodal#258](https://github.com/DiamondLightSource/dodal/pull/258)
Logic for rescaling the beam position has been moved to the OAV device in dodal.
To test:
- Run tests and check they still pass
> Get correct beam position directly from OAV device

- pyproject.toml
Ruff options updated in pyproject as old ones deprecated:
- 'extend-ignore' -> 'lint.extend-ignore'
- 'select' -> 'lint.select'
> Update ruff linter settings in pyproject

- src/mx_bluesky/I24/serial/setup_beamline/pv.py
- src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
Closes #79 
There are still some references to `zlayer` in the code which was used for fluorescence scans but is now legacy. This removes them, as well as the geobrick function in `setup_beamline` which was used for it.
To test:
- all references to `zlayer` have been removed
- tests pass
> Remove legacy code

- src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/I24/serial/parameters/constants.py
- src/mx_bluesky/I24/serial/run_serial.py
> Do not have paths for parameter files as input argument in plans

- .pre-commit-config.yaml
Fixes error in CI
```error: `ruff <path>` has been removed. Use `ruff check <path>` instead.```
`ruff path` has been deprecated, need to update pre-commits
> Fix linting 

- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- tests/I24/serial/fixed_target/test_chip_manager.py
Closes #109 
Closes #51 
A bit of tidying up in `initialise_stages` i.e. the plan run once in awhile when the stages have been off and rebooted.
> Tidy up stages initialisation

- pyproject.toml
- tests/i04/test_thawing.py
> Fix I04 thawing tests

- pyproject.toml
- src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/I24/serial/setup_beamline/pv.py
- src/mx_bluesky/I24/serial/setup_beamline/pv_abstract.py
- src/mx_bluesky/I24/serial/write_nexus.py
- tests/I24/serial/conftest.py
- tests/I24/serial/extruder/test_extruder_collect.py
- tests/I24/serial/fixed_target/test_chip_manager.py
... plus various tidy ups
Closes #115 
(Edit: forgot to add, needs [Dodal652](https://github.com/DiamondLightSource/dodal/pull/652))
> Use dodal devices more widely for I24

- pyproject.toml
- src/mx_bluesky/parameters/__init__.py
- src/mx_bluesky/parameters/components.py
Moves the basic components for parameter models over from Hyperion
Fixes #162
> Move parameter components over from Hyperion

- src/mx_bluesky/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
Cast the values for map type and pump probe when writing the `parameters.json` file.
> Fix parameter file for serial fixed target

- pyproject.toml
Pin blueapi to `0.4.5-a1` until a new release is made, to get [554](https://github.com/DiamondLightSource/blueapi/pull/554)
> Pin blueapi

- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_moveonclick.py
This is a workaround to get `moveonclick` to start. There seems to be an issue connecting both ophyd and ophyd_asynce devices while the plan is running - in this case the OAV device hasn't yet been moved to ophyd_async. 
The workaround instantiates the devices before running the plan.
See [here](https://github.com/bluesky/ophyd-async/issues/548) for details.
> Get moveonclick to start

- src/mx_bluesky/hyperion/parameters/constants.py
- tests/unit_tests/hyperion/parameters/test_parameter_model.py
Hyperion's zebra gridscans work at 250hz, which corresponds to a period of 1/250 (or 0.004) seconds. Our default value here was incorrect
> Correct default exposure time

- src/mx_bluesky/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/198
See `dodal` change at https://github.com/DiamondLightSource/dodal/pull/767
To test:
* Confirm wherever we move the backlight we're putting the move into a sensible group
> Make sure to wait on backlight move

- src/mx_bluesky/beamlines/i24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
Closes #89 
Remove button to save parameters before collection on the edm.
For the moment, still write a parameter file - can be changed later.
> Remove save parameters button

- src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
Fixes #459
Note we're not using the trigger(wait=True) due to https://github.com/bluesky/bluesky/issues/1795
Also confirm that all other problems in the linked issue are covered by other issues.
> Wait between taking snapshots on robot load

- .github/workflows/publish_docker_image.yml
This should fix the `Publish Docker Image` github workflow.
@DominicOram I don't have permission to push an image to the registry, but I've run the action manually in this branch as far as it will go up to the point where it pushes to `ghcr.io` where it fails presumably because I don't have permissions to push to the `diamondlightsource` ghcr.io repo - so you may want to try this before merging.
> Fix the docker image CI build workflow

- pyproject.toml
See https://github.com/DiamondLightSource/python-workflows/issues/180
> Fix unit test failure due to deprecated pkg_resource usage in python-workflows

- pyproject.toml
- src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_wait_for_robot_load_then_centre.py
Fixes #240
Requires https://github.com/DiamondLightSource/dodal/pull/785
To test:
* Confirm new test passes
> Do not reload sample if its already been loaded

- hyperion_other/workflows/test_data/setup.cfg
- pyproject.toml
- src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
- src/mx_bluesky/hyperion/device_setup_plans/setup_panda.py
- tests/conftest.py
- tests/system_tests/hyperion/experiment_plans/test_plan_system.py
- tests/unit_tests/hyperion/device_setup_plans/test_setup_panda.py
Fixes #509 
Updates panda to use `SeqTable.row`
> Support ophyd-async v0.6.0

- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
Fixes #500
To test:
* Confirm new test works
* Confirm all points in the issue were fixed or new issues raised
> Move transmission change in rotation to after detector unstaged

- .pre-commit-config.yaml
> Remove 'no commit to main' from pre-commit hooks

- src/mx_bluesky/hyperion/device_setup_plans/xbpm_feedback.py
> Make it clearer that xbpm decorator is not just for collections

- docs/developer/hyperion/reference/param_hierarchy.puml
- src/mx_bluesky/hyperion/experiment_plans/experiment_registry.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/common/callback_util.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/ispyb_callback_base.py
- src/mx_bluesky/hyperion/parameters/components.py
- src/mx_bluesky/hyperion/parameters/load_centre_collect.py
- tests/conftest.py
- tests/system_tests/conftest.py
- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/system_tests/hyperion/external_interaction/test_ispyb_dev_connection.py
- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
- tests/test_data/parameter_json_files/example_load_centre_collect_params.json
- tests/test_data/parameter_json_files/good_test_load_centre_collect_params.json
- tests/test_data/parameter_json_files/good_test_robot_load_params.json
- tests/unit_tests/hyperion/experiment_plans/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_pin_centre_then_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_and_change_energy.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_then_centre.py
This fix addresses #470 
It also requires GDA jython script change (gerrit change request https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/42628)
To test:
Confirm unit tests pass, and additional system test `test_load_centre_collect_full_plan` work
This code change should support single and multiple rotations, and will be enabled if the property
`gda.mx.hyperion.load_centre_collect.enabled` is set to `true` in domain.properties
> 470 Full experiment plan to replace execute request

- pyproject.toml
- src/mx_bluesky/hyperion/device_setup_plans/setup_zebra.py
- tests/unit_tests/hyperion/device_setup_plans/test_zebra_setup.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
Fixes #546 
Requires dodal change: https://github.com/DiamondLightSource/dodal/pull/823
Also attempts to make the ZebraShutter logic easier to understand
> Configure both inputs on Zebra auto AND gate during setup

- src/mx_bluesky/beamlines/i04/thawing_plan.py
- src/mx_bluesky/beamlines/i24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/beamlines/i24/serial/setup_beamline/setup_detector.py
This fixes the unit tests after the deprecation of `inject()`
see https://github.com/DiamondLightSource/dodal/issues/845
merged in PR
DiamondLightSource/dodal#854
> Replace calls to deprecated inject() with direct factory calls

- .github/workflows/ci.yml
- pyproject.toml
- src/mx_bluesky/hyperion/external_interaction/nexus/nexus_utils.py
- tests/conftest.py
- tests/unit_tests/beamlines/i04/test_thawing.py
- tests/unit_tests/hyperion/device_setup_plans/test_setup_panda.py
- tests/unit_tests/hyperion/device_setup_plans/test_utils.py
- tests/unit_tests/hyperion/device_setup_plans/test_zebra_setup.py
- tests/unit_tests/hyperion/experiment_plans/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_grid_detect_then_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_pin_centre_then_xray_centre_plan.py
This enables CI for Python 3.12 and fixes various associated unit test issues
> Enable CI unit tests for python 3.12

- pyproject.toml
- src/mx_bluesky/hyperion/parameters/components.py
Fixes #461 
To test:
* Confirm unit tests still pass
> Use in-built type for parameter version

- .devcontainer/Dockerfile
- .vscode/mxb-with-core-dependencies.code-workspace
- Dockerfile
- pyproject.toml
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Mapping_py3v1.py
- update devcontainer
- add a workspace with all our core dependencies
- fix some bad use of matplotlib
To test:
- install `pyqt5`, see tests fail on main, pass on this branch
> Make it possible to have an environment with bluesky dev dependencies

- src/mx_bluesky/hyperion/parameters/rotation.py
- tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
This fixes an issue found in system tests where pydantic was reporting failure to serialize `semver.SemanticVersion`.
> Fix MultiRotationScan so that pydantic model_dump_json() works 

- tests/conftest.py
- tests/unit_tests/conftest.py
This PR removes a redundant copy of some code which is a workaround for
https://github.com/pytest-dev/pytest/issues/7409
importantly it now enforces the PYTEST_RAISE environment variable must be set to 1 in order to enable the workaround.
The workaround when enabled causes pytest to bail early at the first error, so before this PR, any failing test would cause all subsequent tests to not be execute, which is undesirable.
> Fix pytest aborting after first encountered test failure

- docs/developer/general/how-to/profile-tests.rst
- docs/developer/general/index.rst
- tests/unit_tests/beamlines/i24/serial/fixed_target/test_ft_collect.py
This shaves off about 10s from the unit test execution time
> Fix slow `fixed_target` test and add some documentation about profiling

- src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
- src/mx_bluesky/hyperion/utils/utils.py
- tests/conftest.py
- tests/test_data/test_beamline_vfm_lat_converter.txt
- tests/unit_tests/hyperion/device_setup_plans/test_dcm_pitch_roll_mirror_adjuster.py
- tests/unit_tests/hyperion/test_utils.py
Fixes #520 
Calculates the Bragg angle directly from the target energy instead of reading from the EPICS PV which is liable to return transient values.
> 520 calculate bragg angle

- tests/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
Similar to https://github.com/DiamondLightSource/dodal/pull/903.
On removing setting the timeouts the tests still passed at the same speed so turns out we're not using them at all. However, it did highlight that `test_detect_grid_and_do_gridscan` was a bit flaky. This was because we were using the "real" backlight positioner, which takes some time to move in/out. Previous tests were doing the move and not waiting on it, then this test would fail on the check. Fixed by using the fake one that moves instantly.
To test:
* Confirm tests still pass at and take roughly the same time as on main
> Remove setting timeouts incorrectly in tests

- tests/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
See https://github.com/DiamondLightSource/dodal/pull/899
To test:
* Update to latest `ophyd-async`:
```
pip uninstall ophyd-async
pip install ophyd-async==0.8.0a5
```
* Confirm tests still pass
> Update types for latest ophyd_async

- pyproject.toml
- src/mx_bluesky/beamlines/i04/thawing_plan.py
- src/mx_bluesky/beamlines/i24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/beamlines/i24/serial/log.py
- src/mx_bluesky/beamlines/i24/serial/setup_beamline/setup_detector.py
- src/mx_bluesky/common/plans/do_fgs.py
- src/mx_bluesky/hyperion/__main__.py
- src/mx_bluesky/hyperion/device_setup_plans/setup_panda.py
- src/mx_bluesky/hyperion/device_setup_plans/setup_zebra.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/oav_snapshot_plan.py
- src/mx_bluesky/hyperion/experiment_plans/pin_centre_then_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py
- tests/unit_tests/common/plan_stubs/test_do_fgs.py
Companion change to https://github.com/DiamondLightSource/dodal/pull/832
> Defer to bluesky.utils MsgGenerator

- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
- src/mx_bluesky/hyperion/experiment_plans/oav_grid_detection_plan.py
- src/mx_bluesky/hyperion/experiment_plans/optimise_attenuation_plan.py
- src/mx_bluesky/hyperion/experiment_plans/pin_tip_centring_plan.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_and_change_energy.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- src/mx_bluesky/hyperion/experiment_plans/set_energy_plan.py
- src/mx_bluesky/hyperion/parameters/rotation.py
- tests/conftest.py
- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/unit_tests/hyperion/device_setup_plans/test_zebra_setup.py
- tests/unit_tests/hyperion/experiment_plans/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_oav_snapshot_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_pin_centre_then_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_pin_tip_centring.py
- tests/unit_tests/hyperion/utils/test_context.py
- Changes our device composites to pydantic dataclasses with config which allows the devices to be used in the plan parameter model generated by BlueApi
- Updates where tests used plain MagicMocks which are now no longer accepted by the valiation. In most cases `spec=RealDeviceType` is sufficient, but when children are needed an ophyd-async `connect(mock=True)` is needed too as spec doesn't find those
> Fix for pydantic 2.10

- tests/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_grid_detect_then_xray_centre_plan.py
Fixes #653
Rather than check that the backlight has finished moving now we just check that we told it to move, which should be a lot less flaky.
To test:
* Run the unit tests all through a few times and confirm they do not fail with the backlight timeout error
> Fix flaky backlight test

- src/mx_bluesky/common/parameters/components.py
- src/mx_bluesky/hyperion/parameters/gridscan.py
- tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
- tests/unit_tests/hyperion/parameters/test_parameter_model.py
This moves the check/creation of the `storage_directory` folder from property access to `DiffractionExperiment` model validation.
This doesn't completely remove duplicated calls to `os.makedirs` but it does reduce it from ~22 to a hopefully more sane number.
But there will still be some duplications as we construct various intermediate parameter instances, all of which have the `storage_directory` parameter.
Fixes #527
> Reduce filesystem access when validating parameters

- tests/unit_tests/hyperion/experiment_plans/test_grid_detect_then_xray_centre_plan.py
Fix for #653 as previous fix #665 was not reliable
> Fix failing backlight detection in unit test `test_detect_grid_and_do_gridscan()`

- src/mx_bluesky/common/parameters/constants.py
- src/mx_bluesky/hyperion/device_setup_plans/smargon.py
- src/mx_bluesky/hyperion/exceptions.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
- src/mx_bluesky/hyperion/experiment_plans/oav_grid_detection_plan.py
- src/mx_bluesky/hyperion/experiment_plans/pin_tip_centring_plan.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_and_change_energy.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/__init__.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/__main__.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/common/callback_util.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/robot_load/ispyb_callback.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/sample_handling/sample_handling_callback.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py
- src/mx_bluesky/hyperion/external_interaction/exceptions.py
- src/mx_bluesky/hyperion/external_interaction/ispyb/exp_eye_store.py
- tests/conftest.py
- tests/system_tests/conftest.py
- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/system_tests/hyperion/external_interaction/test_exp_eye_dev.py
- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_and_change_energy.py
- tests/unit_tests/hyperion/external_interaction/callbacks/robot_load/test_robot_load_ispyb_callback.py
- tests/unit_tests/hyperion/external_interaction/callbacks/rotation/test_ispyb_callback.py
- tests/unit_tests/hyperion/external_interaction/callbacks/sample_handling/test_sample_handling_callback.py
- tests/unit_tests/hyperion/external_interaction/callbacks/test_external_callbacks.py
- tests/unit_tests/hyperion/external_interaction/ispyb/test_expeye_interaction.py
Fixes #595 
Requires #606 
The `blSampleStatus` field in ispyb will now be updated on successful robot load to `LOADED`, when the `load_centre_collect` plan is used.
In the event of the pin not being found or no diffraction, `blSampleStatus` will be updated to `ERROR - sample` to indicate an issue with the sample
If any other error occurs, `blSampleStatus` will be updated to `ERROR - beamline` to indicate a general problem with the beamline.
On normal completion the `blSampleStatus` will be left at `LOADED`
> 595 write to ispyb sample status after collection

- pyproject.toml
- src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_and_change_energy.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/set_energy_plan.py
- tests/conftest.py
- tests/test_data/parameter_json_files/load_centre_collect_params_top_n_by_max_count.json
- tests/unit_tests/hyperion/device_setup_plans/test_dcm_pitch_roll_mirror_adjuster.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_and_change_energy.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_then_centre.py
- tests/unit_tests/hyperion/experiment_plans/test_set_energy_plan.py
This fixes energy change issues discovered during beamline testing #651 
See also DiamondLightSource/dodal#918
1. Energy changes should now result in the VFM yaw and lateral position (x-offset) being set depending on the mirror stripe.
Previously the yaw was unset and the lateral position adjusted according to a lookup-table that was effectively single-valued.
2. The energy change, and individual DCM changes are now serialized because they cannot be done in parallel
3. The timeouts for the yaw, lat operations are increased to 30s from 10s
4. Mirror voltage changes are now serialized instead of being attempted in parallel
5. Energy changes are now done in `robot_load_then_centre` regardless of whether a robot load and/or chi change is performed or not
1. Energy changes work on beamline
2. …
> 651 energy change fixes

- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
This fixes `load_centre_collect_full` to be in line with other plans as it was missed out of the previous PR updating for blueapi changes #564 
Also it uses the `from __future__ import annotations` required to register the plan correctly.
> Fix load_centre_collect imports and annotations

- src/mx_bluesky/common/parameters/components.py
Note this change merges on top of #704 
`pydantic-extra-types` changed the inheritance hierarcy for `SemanticVersion` in the below change, which broke our unit tests
https://github.com/pydantic/pydantic-extra-types/pull/237
This change fixes the following unit test error:
```
ERROR tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py - TypeError: Expected str, bytes, dict, tuple, list, or SemanticVersion instance, but got <class 'semver.version.Version'>
ERROR tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py - TypeError: Expected str, bytes, dict, tuple, list, or SemanticVersion instance, but got <class 'semver.version.Version'>
ERROR tests/unit_tests/hyperion/external_interaction/callbacks - TypeError: Expected str, bytes, dict, tuple, …
```
> Fix unit test borkage due to `pydantic-extra-types` change in 2.10.1

- .github/workflows/_container.yml
- src/mx_bluesky/hyperion/device_setup_plans/manipulate_sample.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/unit_tests/hyperion/device_setup_plans/test_manipulate_sample.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
- utility_scripts/deploy/create_venv.py
- utility_scripts/deploy/deploy_hyperion_to_k8s.sh
- utility_scripts/deploy/deploy_mx_bluesky.py
Fixes #700 
* The deploy script `deploy_hyperion_to_k8s.sh` now deploys the image correctly (but see also #697 where the image is broken, to be fixed in another PR)
* `deploy_mx_bluesky.py` now outputs to the console when remoting to the control server
* Zocalo results below a threshold of 3 are now ignored
* The requested chi is now not ignored if it is 0
Also fixes the following described in #697 :
* Always make sure setuptools_scm is installed when running deploy_hyperion_to_k8s.sh
* Make the version check during k8s deployment more prominent and fix the pathname munging so that it compares correctly
* Fix where the an image was built with `Dockerfile.release` but an image built with `Dockerfile` was the one actually pushed
> 700 fix deployment issues

- src/mx_bluesky/common/parameters/components.py
Addresses #709 
This PR adds the enum value for Metal ID to the experiment type
> Add Metal ID to experiment type

- pyproject.toml
Encountered the pydantic error `TypeError: SemanticVersion() takes no arguments` when running tests; this was due to pydantic-extra-types being at 2.10.0 instead of 2.10.1.
Request to pin this to => 2.10.1
> Pinning pydantic extra types to 2.10.1

- src/mx_bluesky/common/external_interaction/config_server.py
- src/mx_bluesky/common/external_interaction/test_config_server.py
This should fix #620 by checking if the overridden feature flags are defined. Currently, I have this set to raise a ValueError with context of the incorrect passed feature, but maybe we want to simply warn and move on.
> Error when inputting nonexistant feature flags

- pyproject.toml
- src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
- tests/conftest.py
- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
PR [957](https://github.com/DiamondLightSource/dodal/pull/957) in dodal uses `Reference` to reference undulator and dcm devices in undulator_dcm composite. This PR amends mx-bluesky references to undulator_dcm.
> References to undulator and dcm in underlator_dcm device

- utility_scripts/deploy/deploy_mx_bluesky.py
These changes add a --prune-deployments flag, keeping 4 most recent deployments, and deleting the excess if not symlinked to hyperion_stable or hyperion_latest, following #272
> Deployment script deletes old deployments

- tests/system_tests/conftest.py
- tests/test_data/parameter_json_files/example_load_centre_collect_params.json
This adds missing zoom levels to the oav zoom controller following #594 
It also updates the `demand_energy_ev` test data for system test parameters to be valid following #676
> Fix system tests for oav zoom controller and load_centre_collect params

- docs/conf.py
- docs/developer/hyperion/reference/gridscan.puml
- docs/developer/hyperion/reference/param-hierarchy.rst
- pyproject.toml
- src/mx_bluesky/hyperion/experiment_plans/common/xrc_result.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/grid_detection_callback.py
- src/mx_bluesky/hyperion/external_interaction/ispyb/data_model.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
This addresses #221 and improves documentation about the reporting of the Zocalo Results 
See also DiamondLightSource/dodal#958
It also fixes an issue where the bounding box returned in the `XRayCentreResult` is off by 0.5 of a grid-box, however I don't think this impacts anything as this attribute isn't used yet.
> 221 Document gridscan coordinate systems

- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
- tests/system_tests/hyperion/experiment_plans/test_fgs_plan.py
- tests/unit_tests/hyperion/device_setup_plans/test_manipulate_sample.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
Fixes #541 
To test:
* Confirm tests still pass
> Remove initial_xyz and just read in the setup plan

- src/mx_bluesky/common/utils/exceptions.py
- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/sample_handling/sample_handling_callback.py
- tests/unit_tests/hyperion/external_interaction/callbacks/sample_handling/test_sample_handling_callback.py
Relates to #716 
Following a discussion with bluesky team, this PR removes the event handler introduced in 
https://github.com/DiamondLightSource/mx-bluesky/pull/606
in favour of parsing the `reason` field in the RunStop document
> parse the RunStop reason field instead of using events, following discussion with bluesky

- src/mx_bluesky/common/external_interaction/nexus/nexus_utils.py
- src/mx_bluesky/common/external_interaction/nexus/write_nexus.py
- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/rotation/nexus_callback.py
- src/mx_bluesky/hyperion/external_interaction/config_server.py
- src/mx_bluesky/hyperion/parameters/constants.py
- src/mx_bluesky/hyperion/parameters/rotation.py
- tests/conftest.py
- tests/system_tests/hyperion/external_interaction/test_ispyb_dev_connection.py
- tests/unit_tests/common/external_interaction/nexus/test_nexus_utils.py
- tests/unit_tests/hyperion/experiment_plans/test_multi_rotation_scan_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
- tests/unit_tests/hyperion/external_interaction/nexus/test_write_nexus.py
These changes address #247 
* This introduces a new `omega_flip` feature flag that can be set. The default is True. `omega_flip` should be specified according to whether the goniometer omega rotation axis is consistent with the nexus file specification or not https://journals.iucr.org/m/issues/2020/05/00/ti5018/ti5018.pdf
* The `omega_flip` determines the `/entry/sample/transformations/omega` vector in the nexus file and sets it to (-1, 0, 0) if True (in line with GDA) or (+1, 0, 0) if False. It also inverts the motor motions for rotation scans. When `omega_flip` is False, the smargon omega and the omega values in the request have the same sign.
* The `rotation_direction` request parameter now indicates the direction of rotation with respect to the omega sweep specified in the Hyperion …
> Fix rotation omega to match GDA behavior

- tests/unit_tests/beamlines/i24/serial/extruder/test_extruder_collect.py
- tests/unit_tests/beamlines/i24/serial/fixed_target/test_chip_manager.py
- tests/unit_tests/beamlines/i24/serial/setup_beamline/test_setup_beamline.py
- tests/unit_tests/beamlines/i24/serial/setup_beamline/test_setup_detector.py
- tests/unit_tests/hyperion/experiment_plans/test_pin_tip_centring.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_and_change_energy.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
This addresses issue #318.
All motor tests that assert `user_readback == ` should be changed to assert `user_setpoint == `. I have some clarifications of changes as comments below, that I would appreciate thoughts on.
> Assert setpoint in motor tests

- src/mx_bluesky/common/parameters/components.py
This removes the `arbitrary_types_allowed=True` fro `MxBlueskyParameters.model_config`
> Remove unnecessary pydantic model_config arbitrary_types_allowed=True

- tests/unit_tests/hyperion/conftest.py
Fixes
* #533 
This change adjusts the check for unit tests trying to open files so that files in the project folder are allowed
> Fix unit test banned path check to allow access to project folder

- pyproject.toml
- src/mx_bluesky/hyperion/__main__.py
- src/mx_bluesky/hyperion/utils/validation.py
- tests/conftest.py
- tests/system_tests/conftest.py
- tests/system_tests/hyperion/experiment_plans/test_fgs_plan.py
- tests/system_tests/hyperion/experiment_plans/test_plan_system.py
- tests/unit_tests/hyperion/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_grid_detection_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_optimise_attenuation_plan.py
This addresses
* DiamondLightSource/dodal#846
See also dodal PR
* DiamondLightSource/dodal#975
Additionally, this PR also adds unit test duration summary to the end of pytest, this was done because it seems that tests are taking longer, see related issue that is not addressed here
* DiamondLightSource/dodal#973
> Update MX beamlines to use new device factory - Part 1

- pyproject.toml
- src/mx_bluesky/hyperion/utils/validation.py
- tests/conftest.py
- tests/system_tests/hyperion/experiment_plans/test_fgs_plan.py
- tests/system_tests/hyperion/experiment_plans/test_plan_system.py
- tests/unit_tests/common/device_setup_plans/test_read_hardware_for_setup.py
- tests/unit_tests/common/plan_stubs/test_do_fgs.py
- tests/unit_tests/hyperion/device_setup_plans/test_utils.py
This is part of
* DiamondLightSource/dodal#846
This PR updates mx-bluesky to work with changes introduced in dodal PR
* DiamondLightSource/dodal#984
which adds support for ophyd v1 devices to `device_factory`
This PR builds on mx-bluesky PR:
* #735
> Dodal 846 device factory support for ophyd v1

- pyproject.toml
- src/mx_bluesky/common/device_setup_plans/setup_panda.py
- src/mx_bluesky/common/parameters/constants.py
- src/mx_bluesky/definitions.py
- src/mx_bluesky/hyperion/device_setup_plans/setup_panda.py
- src/mx_bluesky/hyperion/parameters/constants.py
- src/mx_bluesky/hyperion/resources/panda/panda-gridscan.yaml
- tests/system_tests/hyperion/test_aperturescatterguard_system.py
- tests/unit_tests/beamlines/i04/test_thawing.py
- tests/unit_tests/common/device_setup_plans/test_setup_panda.py
- tests/unit_tests/common/plan_stubs/test_do_fgs.py
- tests/unit_tests/hyperion/device_setup_plans/test_setup_panda.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
Fixes #706 
- Uses new save-load
- `DeviceCollector` renamed to `init_devices`
Requires https://github.com/DiamondLightSource/dodal/pull/1014
> Use ophyd-async 0.9a2

- src/mx_bluesky/hyperion/experiment_plans/robot_load_and_change_energy.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_and_change_energy.py
Now that dodal issue [1036](https://github.com/DiamondLightSource/dodal/pull/1036) is merged, testing is failing due to an incorrect PV name, so this PR amends the references to the PV.
> Change error_code references for bart robot

- pyproject.toml
- src/mx_bluesky/common/external_interaction/callbacks/xray_centre/ispyb_callback.py
- src/mx_bluesky/common/utils/exceptions.py
- tests/conftest.py
- tests/unit_tests/common/external_interaction/xray_centre/test_ispyb_callback.py
Fixes issue #784 
Added the hotfix @DominicOram wrote in the beamline deployment, and a unit test to test the ispyb callback stop event.
> Make it clear to a user that we're skipping collections after blank XRC

- pyproject.toml
- tests/system_tests/hyperion/external_interaction/callbacks/test_external_callbacks.py
- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/system_tests/hyperion/external_interaction/test_exp_eye_dev.py
- tests/system_tests/hyperion/external_interaction/test_ispyb_dev_connection.py
- tests/system_tests/hyperion/external_interaction/test_nexgen.py
- tests/system_tests/hyperion/external_interaction/test_zocalo_system.py
- tests/test_data/nexus_files/rotation/ins_8_5_expected_output.txt
- tests/test_data/nexus_files/rotation_unicode_metafile/ins_8_5_expected_output.txt
This addresses 
* #632 
and builds on
* #793
it also requires
* DiamondLightSource/dodal#1049
* https://gitlab.diamond.ac.uk/MX-GDA/hyperion-system-testing/-/merge_requests/2
These changes fix up and enable the following system tests when the containerised system tests are run:
* `test_external_callbacks`   -- external callback launching
* `test_exp_eye_dev` -- ExpEye integration
* `test_ispyb_dev_connection` -- ISPyB integration
* `test_nexgen` -- imginfo integration
* `test_zocalo_system` -- zocalo integration (using the "fake" zocalo
`test_config_service` is not currently included, to include this ideally we should make changes to the `daq-config-server` images so that instead of creating dev/production images with hard-coded configurations, it pushes a single set of images which are …
> 632 Add external interaction system tests to the containerised system tests

- .github/CONTRIBUTING.md
As per recent slack thread, it would be good to let others know when a review is in process by assigning yourself the PR when you begin to review it. Added docs which say this
> Add to docs on code reviews

- tests/unit_tests/hyperion/external_interaction/callbacks/rotation/test_ispyb_callback.py
We pass `dummy_rotation_params` to our tests, but this is never explicitly used, so this is now removed.
At some point, the fixture `rotation_start_outer_doc_without_snapshots` was used to set `dummy_rotation_params.ispyb_extras.xtal_snapshots_omega_start = None` (changes [here](https://github.com/DiamondLightSource/hyperion/pull/1437/files#diff-93a54e1eb3d5894e18d8dd8cdf2d028e670d39823917e71890f51e1c726d1695)), but currently this fixture simply returns `test_rotation_start_outer_document`, which populates `"mx_bluesky_parameters": dummy_rotation_params.model_dump_json()`.  Looks like `xtal_snapshots_omega_start` was removed in #493, so this PR removes the now redundant test `test_activity_gated_start_with_snapshot_parameters`.
1. Confirm tests pass with expected behavior
> Remove unused dummy_rotation_params from callback tests

- src/mx_bluesky/common/external_interaction/callbacks/common/plan_reactive_callback.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/sample_handling/sample_handling_callback.py
- tests/unit_tests/hyperion/external_interaction/callbacks/sample_handling/test_sample_handling_callback.py
Fixes
* #787 
1. `BLSampleStatus` should now be logged against the correct sample instead of only the first sample
2. BLSampleStatus updates should now only be triggered once on an exception instead of once for each level of bluesky run nesting it escapes.
> 787 Update sample status field correctly

- pyproject.toml
- tests/unit_tests/common/external_interaction/xray_centre/test_nexus_handler.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
- tests/unit_tests/hyperion/external_interaction/callbacks/test_rotation_callbacks.py
- tests/unit_tests/hyperion/parameters/test_parameter_model.py
Fixes #851 
This PR should amend all tests that use `with pytest.raises()..`, such that the context manager only contains a single line of code (i.e., the line that raises the expected exception). This follows the newly added ruff linting rule [PT012](https://docs.astral.sh/ruff/rules/pytest-raises-with-multiple-statements/). The main reason we are doing this is to avoid accidentally asserting within a `pytest.raises()` block, as this never runs, but looks like it does.
1. Check all instances of `with pytest.raises()..` accounted for.
2. Confirm tests still pass.
> Enforce pytest.raises() is simple

- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
Enables the test in
* #761 
to actually be selected for running in the containerised system tests
> Enable the zocalo bounds check system test

- src/mx_bluesky/beamlines/i04/redis_to_murko_forwarder.py
- tests/unit_tests/beamlines/i04/test_redis_to_murko_forwarder.py
Fixes #804
Formalized the idea of just warning and moving on. I think this is fine because I haven't seen the issue re-occur over the last week and we're streaming so many images to murko if we're a bit lossy it doesn't matter.
1. Confirm test passes
> Do not forward invalid images to murko

- src/mx_bluesky/beamlines/i04/redis_to_murko_forwarder.py
- tests/unit_tests/beamlines/i04/test_redis_to_murko_forwarder.py
Fixes #683
Needed to use pickle instead of json as the murko results contain numpy arrays.
1. Confirm tests still pass
> Put full murko results in redis as pickled objects

- pyproject.toml
- src/mx_bluesky/common/external_interaction/callbacks/common/ispyb_callback_base.py
- src/mx_bluesky/common/external_interaction/callbacks/common/zocalo_callback.py
- src/mx_bluesky/common/external_interaction/callbacks/xray_centre/nexus_callback.py
Fixes #256
Link to dodal PR: #[1100](https://github.com/DiamondLightSource/dodal/pull/1100)
1. Search for the walrus operator inside the codebase.
2. Confirm it never occurs inside an assert, other than in tests.
3. If possible, run tests with the -O flag, possible using [dissert](https://github.com/boothby/dissert).
> (#256) Remove walrus operator from asserts

- pull_request_template.md
Fixes #899
1. Check that the template now includes 'pyproject.toml' rather than 'setup.cfg'.
2. Once merged, could check that this change is reflected when making a new PR.
> (#899) Replace 'setup.cfg' with 'pyproject.tml' in PR template

- .github/CONTRIBUTING.md
Fixes #898
1. Check `.github/CONTRIBUTING.md`
2. Check the instructions under 'Developing mx-bluesky and dodal' are clear and correct.
> (#898) Add docs on developing dodal alongside MXB

- pyproject.toml
- src/mx_bluesky/hyperion/device_setup_plans/setup_panda.py
- tests/system_tests/hyperion/external_interaction/test_agamemnon.py
Fixes breakages caused by upstream changes:
* DiamondLightSource/dodal#1085
* bluesky/ophyd-async#838
plus a test failure in our own code caused by our use of `DeepDiff` on pydantic models which also triggers the problematic deprecation warnings
N.b. pydantic 2.11 is currently in pre-release but I have it accidentally installed due to having to revert some other package in my venv.
1. Tests pass
> Fixes for dodal 1085 breakage, pydantic deprecation warnings

- .github/workflows/_test.yml
Increases the CI unit test timeout, doubles it to 2s from 1s, as was seeing too  many spurious CI failures
> Bump the CI test timeout to be more lenient

- tests/conftest.py
Fixes unit tests broken by
* DiamondLightSource/dodal#1193
by patching the i03 default beamline_parameters file
> Fix unit tests broken by DiamondLightSource/dodal#1193

- tests/conftest.py
- tests/unit_tests/beamlines/i23/test_serial.py
- tests/unit_tests/conftest.py
- tests/unit_tests/hyperion/conftest.py
Fixes an issue where `RunEngine` fixtures were creating event loops that were never cleaned up.
This led to 
```
File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/socket.py", line 608, in socketpair
a, b = _socket.socketpair(family, type, proto)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files
```
being reported in unit tests where `ulimit -n` was set too low (1024)
1. Unit tests pass
> Unit tests: Ensure that run engine event loop always terminates

- pyproject.toml
- src/mx_bluesky/common/utils/log.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/__main__.py
- tests/conftest.py
- tests/unit_tests/common/utils/test_log.py
Fixes #1039
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/1209
1. Confirm tests still pass and in prod debug logs will be going into `/tmp`
> Move debug logs into `/tmp`

- docs/developer/hyperion/reference/readme.md
- run_hyperion.sh
- src/mx_bluesky/hyperion/__main__.py
- src/mx_bluesky/hyperion/parameters/cli.py
- src/mx_bluesky/hyperion/utils/context.py
- tests/unit_tests/hyperion/test_main_system.py
- utility_scripts/docker/entrypoint.sh
This removes the `--skip-startup-connection` option, which no longer does anything, since 
* https://github.com/DiamondLightSource/blueapi/pull/751
which implements ADR
https://diamondlightsource.github.io/blueapi/main/explanations/decisions/0005-connect-devices.html
This also removes the preloading of devices that occurs by calling the `create_devices` methods of all the entry points, since standard blueapi beamline loading already connects all the devices.
Also solves the following outdated issues:
* #253 
* #284 
1. Tests pass
2. mx-bluesky still launches
> Remove --skip-startup-connection startup option and associated device warmup

- src/mx_bluesky/common/parameters/gridscan.py
- src/mx_bluesky/hyperion/parameters/gridscan.py
- tests/unit_tests/hyperion/external_interaction/nexus/test_write_nexus.py
Fixes #1058
Added `detector_params` to `GridCommon` to make it a concrete class, and changed `GridCommonWithHyperionDetectorParams`and `HyperionSpecifiedThreeDGridScan` to use the `detector_params` they now inherit.
1. Confirm this is the right thing to do
2. Check Hyperion classes still function as intended
> Make GridCommon class concrete

- docs/developer/hyperion/reference/readme.md
- helmcharts/hyperion/templates/deployment.yaml
- helmcharts/hyperion/values.yaml
- run_hyperion.sh
- src/mx_bluesky/common/utils/log.py
- src/mx_bluesky/hyperion/__main__.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/__main__.py
- src/mx_bluesky/hyperion/parameters/cli.py
- src/mx_bluesky/hyperion/utils/context.py
- tests/conftest.py
- tests/unit_tests/common/utils/test_log.py
- tests/unit_tests/hyperion/test_main_system.py
- utility_scripts/docker/entrypoint.sh
Fixes
* #751 
Note that the issue was likely caused by launching hyperion directly with the --dev parameter, not via `run_hyperion.sh`
Changes to the `run_hyperion.sh` script consist of the following minor tidyups/fixes:
* Better documentation of options, and don't defer to python for generating the first bit of the help text
* Always specify `ZOCALO_CONFIG` and `ISPYB_CONFIG` with `--dev` so that we don't try to talk to production servers
* Require BEAMLINE to be always set in the environment or specified as a parameter
This PR also changes `--dev-mode` so that now it creates mock devices instead of real ones, ensuring that hyperion can be started without access to the beamline network.
This also addresses some issues arising from
* #1039 
* DEBUG_LOG_DIR can now be specified for use by …
> 751 fix run hyperion in dev mode

- docs/developer/hyperion/deploying-hyperion.rst
- helmcharts/hyperion/templates/deployment.yaml
- helmcharts/hyperion/templates/zocalo-config.yaml
- helmcharts/hyperion/values.yaml
- utility_scripts/deploy/deploy_mx_bluesky_app_to_k8s.sh
Fixes [python-dlstbx#291](https://github.com/DiamondLightSource/python-dlstbx/issues/291)
1. Add secrets matching the names of zocalo.secrets added into `values.yaml` into the desired namespace
2. Install helm chart
3. Confirm that communication with zocalo works as expected
> Add zocalo config to helm chart as a configmap

- utility_scripts/dls_dev_env.sh
Fixes issues with `setuptools_dso` trying use `wheel` badly. If `wheel` is installed it will try and use it where it is depreciated and you get an error like:
```
ImportError while loading conftest '/scratch/ffv81422/bluesky_work/dodal/conftest.py'.
conftest.py:14: in <module>
from ophyd.status import Status
.venv/lib/python3.11/site-packages/ophyd/__init__.py:89: in <module>
set_cl()
.venv/lib/python3.11/site-packages/ophyd/__init__.py:24: in set_cl
set_cl(c_type, pv_telemetry=pv_telemetry)
.venv/lib/python3.11/site-packages/ophyd/__init__.py:39: in set_cl
import epicscorelibs.path.pyepics  # noqa
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.venv/lib/python3.11/site-packages/epicscorelibs/path/__init__.py:6: in <module>
from setuptools_dso.runtime import dylink_prepare_dso, find_dso …
```
> Remove unrequired wheel install

- src/mx_bluesky/hyperion/experiment_plans/hyperion_flyscan_xray_centre_plan.py
- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_hyperion_flyscan_xray_centre_plan.py
Fixes
* #1141 
This ensures that the call to reset the `dev_shm_enable` PV occurs with a wait such that any `contingency_wrapper` does not attempt to make a concurrent write to the PV
1. Do thing x
> (#1141) Fix another set call in progress for dev_shm_enable on CrystalNotFoundException

- pyproject.toml
- src/mx_bluesky/common/experiment_plans/common_flyscan_xray_centre_plan.py
- src/mx_bluesky/common/external_interaction/ispyb/ispyb_store.py
- src/mx_bluesky/common/external_interaction/nexus/write_nexus.py
- src/mx_bluesky/common/parameters/components.py
- src/mx_bluesky/common/xrc_result.py
- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
- src/mx_bluesky/hyperion/parameters/load_centre_collect.py
- src/mx_bluesky/hyperion/parameters/rotation.py
- tests/conftest.py
- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/system_tests/hyperion/external_interaction/test_agamemnon.py
- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
- tests/test_data/parameter_json_files/good_test_multi_rotation_scan_parameters.json
- tests/test_data/parameter_json_files/good_test_one_multi_rotation_scan_parameters.json
- tests/test_data/parameter_json_files/good_test_one_multi_rotation_scan_parameters_nomove.json
- tests/unit_tests/common/experiment_plans/test_change_aperture_then_move_plan.py
- tests/unit_tests/common/experiment_plans/test_common_flyscan_xray_centre_plan.py
- tests/unit_tests/conftest.py
- tests/unit_tests/hyperion/experiment_plans/common/test_flyscan_result.py
- tests/unit_tests/hyperion/experiment_plans/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_hyperion_flyscan_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
- tests/unit_tests/hyperion/external_interaction/callbacks/rotation/test_ispyb_callback.py
- tests/unit_tests/hyperion/external_interaction/callbacks/test_rotation_callbacks.py
- tests/unit_tests/hyperion/external_interaction/test_agamemnon.py
Fixes #1038
Link to dodal PR (if required):
* https://github.com/DiamondLightSource/dodal/pull/1298
Implements the following changes:
* The sample ID is now retrieved from Zocalo processing results. 
* The `sample_id` attribute in the hyperion request parameters is now taken to be the "parent" sample id under which robot load and gridscan results are reported in Ispyb and for which BLSampleStatus field is set in the event of sample or beamline errors
* There is a new selection algorithm `TopNByMaxCountForEachSample` that can be specified in `select_centres` in the request, this selects the top n diffracting centres for each sample ID that is returned by zocalo.
* If no sample ID attribution is made in a result from zocalo, a warning is logged and the diffracting centre is skipped.
1. …
> Use sample id from zocalo after XRC

- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- src/mx_bluesky/hyperion/__main__.py
- tests/unit_tests/hyperion/test_main_system.py
Fixes #1136 
This formats parameter requests more nicely in graylog, by correctly expanding the output of `format_exception()`
1. Do thing x
> Format request parameter exceptions nicely in graylog

- src/mx_bluesky/beamlines/i24/serial/blueapi_config.yaml
Fixes #1168 
1. Start a blueapi server with 
```bash
blueapi -c src/mx_bluesky/beamlines/i24/serial/blueapi_config.yaml serve
``` 
and verify it connects without configuration errors
> Update I24 blueapi config

- src/mx_bluesky/beamlines/i04/experiment_plans/i04_grid_detect_then_xray_centre_plan.py
This function is used in other Hyperion plans to instantiate devices but in this case device instantiation is done for us by BlueAPI so we do not need it.
1. Confirm tests pass
> Remove unused function for i04 grid scans

- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
* Update the expected wavelength in load_centre_collect_full test now that the DCM fixture motors are all patched.
* Make fake zocalo results come from the GPU now that we are ignoring CPU results
1. System tests pass
https://gitlab.diamond.ac.uk/MX-GDA/hyperion-system-testing/-/jobs/267350
> Fix broken system tests

- .github/workflows/_test.yml
- docs/developer/general/how-to/dev-ops/run-tests.rst
- pyproject.toml
- tests/conftest.py
Disable code coverage when running unit tests locally; this provides a signfiicant (~27s) speedup on my workstation.
It also seems to eliminate the 1s timeout failures when running the tests.
Code coverage is still enabled for Github CI tests.
This also adds a one line change to close the RunEngine fixture event loop after usage; this was generating some confusing error messages when I was writing unit tests, due to the `ResourceWarning`/`UnraisableExceptionWarning` errors which occurred when the event loop was eventually garbage collected.
1. Tests pass
2. GH CI still generates code coverage
> Only enable code coverage reporting in GitHub CI

- pyproject.toml
- tests/conftest.py
Fixes unit tests against the latest ophyd-async (v0.13.2) following
* bluesky/ophyd-async#1032
1. Unit tests pass
> Fix unit tests following ophyd-async changes

- tests/system_tests/hyperion/external_interaction/conftest.py
Fixes breakage in `test_load_centre_collect_generate_rotation_snapshots()`.
This was caused by `bps.wait()` being patched, which silently elided a wait in `rotation_scan_plan.py`:
``        yield from bps.wait(CONST.WAIT.MOVE_GONIO_TO_START)``
This wait was responsible for ensuring that a preding `CombinedMove` on the smargon completed; changes to the smargon to include checks for motor limits changed the timing for this move and meant that the snapshot was no longer in the correct position.
1. System tests pass
https://gitlab.diamond.ac.uk/MX-GDA/hyperion-system-testing/-/jobs/270594
> Fix for snapshot system test

- tests/unit_tests/hyperion/test_baton_handler.py
Fixes unit tests for breakage due to change in latest blueapi where `BlueskyContext` introduced a new attribute that broke existing constructor calls.
1. Do thing x
> Fix BlueskyContext constructor calls for breakage in new blueapi

- src/mx_bluesky/beamlines/i04/experiment_plans/i04_grid_detect_then_xray_centre_plan.py
- src/mx_bluesky/common/experiment_plans/common_flyscan_xray_centre_plan.py
- src/mx_bluesky/common/experiment_plans/inner_plans/do_fgs.py
- src/mx_bluesky/common/external_interaction/callbacks/common/ispyb_callback_base.py
- src/mx_bluesky/common/external_interaction/callbacks/common/zocalo_callback.py
- src/mx_bluesky/common/external_interaction/callbacks/xray_centre/ispyb_callback.py
- src/mx_bluesky/common/external_interaction/callbacks/xray_centre/ispyb_mapping.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/__main__.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
- tests/conftest.py
- tests/system_tests/conftest.py
- tests/system_tests/hyperion/external_interaction/callbacks/test_external_callbacks.py
- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/system_tests/hyperion/external_interaction/test_ispyb_dev_connection.py
- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
- tests/system_tests/hyperion/external_interaction/test_zocalo_system.py
- tests/unit_tests/common/experiment_plans/inner_plans/test_do_fgs.py
- tests/unit_tests/common/experiment_plans/test_common_flyscan_xray_centre_plan.py
- tests/unit_tests/common/external_interaction/callbacks/test_zocalo_handler.py
- tests/unit_tests/common/external_interaction/xray_centre/test_ispyb_callback.py
- tests/unit_tests/common/external_interaction/xray_centre/test_ispyb_handler.py
- tests/unit_tests/common/external_interaction/xray_centre/test_nexus_handler.py
- tests/unit_tests/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
Fixes #1290 
Link to dodal PR (if required): 
* DiamondLightSource/dodal#1576
1. Gridscans should now work regardless of the order of grid detection / grid snapshot being taken
2. A side effect of this fix is that the ordering of the gridscan data collections will vary in synchweb, sometimes xy will be first, sometimes xz plane will be first
3. In most cases, xz will be first (lowest on screen), the exception that I can think of is if the sample is already loaded but a gridscan is needed again, and the previous rotation left the smargon in a different omega.
* System tests require a rebuild of the zocalo test image due to a bug in fake zocalo which didn't return the DataCollectionGroupId
> Fix for gridscans failing due to ordering of grid detection

- tests/unit_tests/beamlines/i24/jungfrau_commissioning/test_plan_utils.py
This hopefully fixes test failures in `test_fly_jungfrau` as seen here
https://github.com/DiamondLightSource/mx-bluesky/actions/runs/18161240174/job/51693484886?pr=1282
It adds asyncio.sleep(0) to give scheduler time to register second await - I'm not 100% sure why this is necessary but suspect it is connected with the run engine being on a different thread to the main event loop.
1.Tests pass
> Fix jungfrau spurious test failures
