- .github/workflows/code.yml
- .vscode/mx-bluesky.code-workspace
- dls_dev_setup.sh
- pyproject.toml
- Add dodal to dependencies 
- Install dodal in .venv
- Set up vscode workspace
> Add dodal 

- .gitignore
- deploy/deploy_edm_for_ssx.sh
- pyproject.toml
- src/mx_bluesky/I24/serial/extruder/EX-gui-edm/DiamondExtruder-I24-py3v1.edl
- src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/CustomChip_py3v1.edl
- src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
- src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/ME14E-motors.edl
- src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/MappingLite-oxford_py3v1.edl
- src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/PMAC_Command.edl
- src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/pumpprobe-py3v1.edl
- src/mx_bluesky/I24/serial/run_serial.py
- src/mx_bluesky/I24/serial/run_ssx.sh
- src/mx_bluesky/I24/serial/set_visit_directory.sh
Closes #27 and closes #29  
- Have the edm point to the correct scripts/edms
- Have a bash script to run extruder/fixed target experiment
Set up two options for running, one using a bash script and the other entry points, one to be removed after testing and discussion with beamline staff.
> Set up a first deployment for testing I24 ssx

- src/mx_bluesky/I24/serial/set_visit_directory.sh
Closes #35 
Instead of passing value from the command line, have a file that can be modified by beamline staff and read visit from there.
> Read current visit from file

- deploy/deploy_mxbluesky.py
- dls_dev_setup.sh
- pyproject.toml
> Set up a deploy script for the mx_bluesky release

- src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- tests/I24/serial/extruder/test_extruder_collect.py
> Use a spare soft input on the Zebra for the laser check

- pyproject.toml
- src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
- tests/I24/serial/conftest.py
- tests/I24/serial/extruder/test_extruder_collect.py
- tests/I24/serial/setup_beamline/test_zebra_plans.py
See [Dodal#382](https://github.com/DiamondLightSource/dodal/pull/382).
Zebra device has been converted to ophyd_async. Update plans and tests accordingly.
**To test:**
- Run unit tests and confirm they pass
> Update plans to use new Zebra device

- dls_dev_setup.sh
- Install environment with python 3.11
- Upgrade pip
- Install wheel
> Update install script

- .vscode/settings.json
- pyproject.toml
- src/mx_bluesky/i04/thawing_plan.py
- tests/i04/test_thawing.py
> i04 thawing plan

- pyproject.toml
- src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- tests/I24/serial/conftest.py
- tests/I24/serial/extruder/test_extruder_collect.py
- tests/I24/serial/fixed_target/test_ft_collect.py
Closes #110 
Needs [Dodal#623](https://github.com/DiamondLightSource/dodal/pull/623)
> Use shutter device in I24 serial plans

- src/mx_bluesky/I24/serial/extruder/EX-gui-edm/DetStage.edl
- src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DetStage.edl
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/I24/serial/log.py
Hotfixes while testing on I24 on 02/07/2024.
> Beamline testing fixes

- src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/I24/serial/fixed_target/ft_utils.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Mapping_py3v1.py
- src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_StartUp_py3v1.py
- src/mx_bluesky/I24/serial/parameters/__init__.py
- src/mx_bluesky/I24/serial/parameters/experiment_parameters.py
- src/mx_bluesky/I24/serial/parameters/utils.py
- src/mx_bluesky/I24/serial/set_visit_directory.sh
- src/mx_bluesky/I24/serial/write_nexus.py
- tests/I24/serial/fixed_target/conftest.py
- tests/I24/serial/fixed_target/test_chip_startup.py
- tests/I24/serial/fixed_target/test_ft_collect.py
- tests/I24/serial/fixed_target/test_utils.py
- tests/I24/serial/parameters/test_utils.py
Closes #118 
This spawned #122
> Add General Purpose PVs to parameter model

- pyproject.toml
- src/mx_bluesky/I24/serial/log.py
- src/mx_bluesky/I24/serial/run_extruder.sh
- src/mx_bluesky/I24/serial/run_fixed_target.sh
> Beamline test hotfixes

- src/mx_bluesky/beamlines/i24/serial/fixed_target/FT-gui-edm/MappingLite-oxford_py3v1.edl
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
Closes #160 
- Remove input chip from `upload_parameters` as used only by oxford-type chips
- Update edm
> Remove input argument from `upload_parameters`

- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- tests/unit_tests/beamlines/i24/serial/fixed_target/test_ft_collect.py
- tests/unit_tests/beamlines/i24/serial/setup_beamline/test_setup_beamline.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_multi_rotation_scan_plan.py
Speeds up the unit tests.
To test:
* Run unit tests on main, confirm they take ~60s
* Run unit tests on this branch, confirm they take ~30s
* Confirm tests still all pass
> Speed up unit tests

- src/mx_bluesky/hyperion/device_setup_plans/manipulate_sample.py
- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- src/mx_bluesky/hyperion/parameters/constants.py
- tests/system_tests/hyperion/external_interaction/test_ispyb_dev_connection.py
- tests/unit_tests/hyperion/experiment_plans/test_grid_detect_then_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
Replaces https://github.com/DiamondLightSource/hyperion/pull/1529 and fixes https://github.com/DiamondLightSource/mx-bluesky/issues/206
> Stage eiger asynchronously on a rotation plan

- pyproject.toml
- src/mx_bluesky/beamlines/i04/__init__.py
- src/mx_bluesky/beamlines/i04/thawing_plan.py
- tests/unit_tests/beamlines/i04/test_thawing.py
Fixes #195
See dodal change at https://github.com/DiamondLightSource/dodal/pull/765
To test:
* Confirm tests pass
* Confirm addresses points in issue
> Fixes for thawing plan based on beamline testing

- helmchart/templates/deployment.yaml
- helmchart/values.yaml
- utility_scripts/deploy/deploy_hyperion_to_k8s.sh
Add data dir to helmchart, make log dir writable, fix project dir version prefix
> Fixes to kubernetes deployment helmcharts

- pyproject.toml
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- tests/unit_tests/beamlines/i24/serial/fixed_target/test_ft_collect.py
Uses change in [Dodal#771](https://github.com/DiamondLightSource/dodal/pull/773)
> Use pmac abort program

- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/rotation/ispyb_mapping.py
- src/mx_bluesky/hyperion/parameters/components.py
- src/mx_bluesky/hyperion/parameters/rotation.py
- tests/conftest.py
- tests/system_tests/hyperion/external_interaction/test_ispyb_dev_connection.py
- tests/test_data/parameter_json_files/good_test_rotation_scan_parameters.json
- tests/test_data/parameter_json_files/good_test_rotation_scan_parameters_nomove.json
- tests/unit_tests/hyperion/external_interaction/callbacks/rotation/test_ispyb_callback.py
Fixes #492
To test:
* Confirm tests still pass
* Confirm `pytest tests/system_tests/hyperion/external_interaction/test_ispyb_dev_connection.py` passes
> Remove unused ispyb extras

- codecov.yml
- pyproject.toml
- src/mx_bluesky/beamlines/i24/serial/extruder/EX-gui-edm/DetStage.edl
- src/mx_bluesky/beamlines/i24/serial/extruder/EX-gui-edm/DiamondExtruder-I24-py3v1.edl
- src/mx_bluesky/beamlines/i24/serial/fixed_target/FT-gui-edm/CustomChip_py3v1.edl
- src/mx_bluesky/beamlines/i24/serial/fixed_target/FT-gui-edm/DetStage.edl
- src/mx_bluesky/beamlines/i24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
- src/mx_bluesky/beamlines/i24/serial/fixed_target/FT-gui-edm/MappingLite-oxford_py3v1.edl
- src/mx_bluesky/beamlines/i24/serial/fixed_target/FT-gui-edm/pumpprobe-py3v1.edl
- src/mx_bluesky/beamlines/i24/serial/run_serial.py
Temporarily re-added the devices to the shell commands in the edm scripts because of [this blueapi issues](https://github.com/DiamondLightSource/blueapi/issues/647). To be removed once fixed and inject works again
> I24 serial: Beamline test fixes

- tests/unit_tests/hyperion/device_setup_plans/test_setup_oav.py
See https://github.com/DiamondLightSource/dodal/pull/803
> Remove unnecessary test for zoom and flatfield

- src/mx_bluesky/hyperion/device_setup_plans/read_hardware_for_setup.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/ispyb_callback_base.py
- tests/system_tests/hyperion/experiment_plans/test_fgs_plan.py
- tests/system_tests/hyperion/experiment_plans/test_plan_system.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
- tests/unit_tests/hyperion/external_interaction/callbacks/conftest.py
- tests/unit_tests/hyperion/external_interaction/callbacks/rotation/test_ispyb_callback.py
- tests/unit_tests/hyperion/external_interaction/callbacks/xray_centre/test_ispyb_callback.py
Fixes #495.
Reads the dcm energy before collection and updates ispyb accordingly
* Confirm tests pass
> Put wavelength into ispyb earlier

- pyproject.toml
- tests/conftest.py
- tests/system_tests/hyperion/experiment_plans/test_fgs_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
Fixes #539
Dodal PR: https://github.com/DiamondLightSource/dodal/pull/873
To test:
* Confirm tests still pass
> Update tests to match new name of odin function

- src/mx_bluesky/beamlines/i24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/beamlines/i24/serial/parameters/__init__.py
- src/mx_bluesky/beamlines/i24/serial/parameters/experiment_parameters.py
- src/mx_bluesky/beamlines/i24/serial/write_nexus.py
- tests/unit_tests/beamlines/i24/serial/conftest.py
- tests/unit_tests/beamlines/i24/serial/extruder/test_extruder_collect.py
- tests/unit_tests/beamlines/i24/serial/fixed_target/conftest.py
- tests/unit_tests/beamlines/i24/serial/test_write_nexus.py
Fixes #674
To test:
* Confirm tests pass and code is cleaner
> Tidy call_nexgen in i24 SSX

- run_hyperion.sh
- src/mx_bluesky/common/parameters/constants.py
Fixes #650
See also https://github.com/DiamondLightSource/dodal/pull/909
To test:
* Confirm that all points in #640 have been addressed by this PR or will be addressed in others
> Fixes from beamline testing

- pyproject.toml
- src/mx_bluesky/beamlines/i24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- src/mx_bluesky/hyperion/device_setup_plans/read_hardware_for_setup.py
- src/mx_bluesky/hyperion/device_setup_plans/xbpm_feedback.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/optimise_attenuation_plan.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_and_change_energy.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- src/mx_bluesky/hyperion/experiment_plans/set_energy_plan.py
- tests/conftest.py
- tests/system_tests/hyperion/external_interaction/conftest.py
- tests/unit_tests/hyperion/test_main_system.py
Accompanies the change for https://github.com/DiamondLightSource/dodal/pull/969
> Update attenuator import paths and names

- src/mx_bluesky/common/external_interaction/callbacks/common/ispyb_callback_base.py
- src/mx_bluesky/common/external_interaction/callbacks/xray_centre/ispyb_callback.py
- src/mx_bluesky/common/external_interaction/ispyb/exp_eye_store.py
- src/mx_bluesky/common/external_interaction/ispyb/ispyb_store.py
- src/mx_bluesky/common/parameters/components.py
- src/mx_bluesky/common/parameters/gridscan.py
- src/mx_bluesky/common/plans/do_fgs.py
- src/mx_bluesky/common/utils/log.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
- src/mx_bluesky/hyperion/experiment_plans/oav_grid_detection_plan.py
- src/mx_bluesky/hyperion/experiment_plans/pin_centre_then_xray_centre_plan.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/common/callback_util.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/robot_load/ispyb_callback.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
- src/mx_bluesky/hyperion/parameters/gridscan.py
- src/mx_bluesky/hyperion/parameters/load_centre_collect.py
- src/mx_bluesky/hyperion/parameters/rotation.py
- tests/conftest.py
- tests/system_tests/hyperion/external_interaction/test_nexgen.py
- tests/unit_tests/common/external_interaction/xray_centre/test_ispyb_mapping.py
- tests/unit_tests/hyperion/conftest.py
- tests/unit_tests/hyperion/experiment_plans/test_grid_detection_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_multi_rotation_scan_plan.py
- tests/unit_tests/hyperion/external_interaction/callbacks/rotation/test_ispyb_callback.py
- tests/unit_tests/hyperion/external_interaction/test_write_rotation_nexus.py
- utility_scripts/generate_plantuml.py
> Make ruff happy

- pyproject.toml
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/external_interaction/config_server.py
- src/mx_bluesky/hyperion/parameters/constants.py
- src/mx_bluesky/hyperion/parameters/gridscan.py
- tests/unit_tests/hyperion/parameters/test_parameter_model.py
Fixes #771 
Needs https://github.com/DiamondLightSource/dodal/pull/1025
To Test
* Confirm tests pass
> 771 use gpu results

- pyproject.toml
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_moveonclick.py
- src/mx_bluesky/beamlines/i24/serial/setup_beamline/setup_beamline.py
- tests/conftest.py
- tests/unit_tests/beamlines/i24/serial/conftest.py
- tests/unit_tests/conftest.py
- tests/unit_tests/hyperion/conftest.py
This PR updates mx-bluesky to work with dodal changes in
* DiamondLightSource/dodal#990
which addresses
* DiamondLightSource/dodal#846
for i24
This PR builds on top of
* #735 
* ~#743~
> Dodal 846 convert i24 to use device factory

- pyproject.toml
- tests/unit_tests/beamlines/i04/test_thawing.py
This PR is part of a series of changes to address
* DiamondLightSource/dodal#846
This PR updates mx-bluesky to work with changes introduced in
* DiamondLightSource/dodal#986
This PR builds on mx-bluesky PRs
* #735 
* #743
> Dodal 846 update i04 to use device_factory

- tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_then_centre.py
- tests/unit_tests/hyperion/test_main_system.py
See review on https://github.com/DiamondLightSource/mx-bluesky/pull/763
Feel free to dismiss as too nit-picky
To test:
* Code is maybe cleaner?
* Behaviour unchanged
> Nit comments on fixing box size

- Dockerfile.release
- utility_scripts/build_docker_image.sh
- utility_scripts/deploy/deploy_hyperion_to_k8s.sh
- utility_scripts/deploy/deploy_mx_bluesky.py
> Fix deployment scripts

- src/mx_bluesky/common/parameters/constants.py
- tests/unit_tests/hyperion/device_setup_plans/test_setup_panda.py
Part of https://github.com/DiamondLightSource/mx-bluesky/issues/826
1. Confirm new test fails on `main` and passes here
> Fix path to panda settings

- pyproject.toml
- src/mx_bluesky/beamlines/i04/redis_to_murko_forwarder.py
- tests/unit_tests/beamlines/i04/test_redis_to_murko_forwarder.py
Part of #875
1. Run `pyright .` using the latest `pyright` version
2. Confirm there is a problem in the redis forwarder on main but not on this branch
> Fix pyright issue

- pyproject.toml
- tests/unit_tests/hyperion/conftest.py
Fixes #875
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/1093 (not strictly required but easier to do at the same time)
1. Install a new dev env (`./utility_scripts/dls_dev_env.sh`)
2. Run `pyright .` and confirm it passes
> Unpin and fix pyright errors

- pyproject.toml
- src/mx_bluesky/beamlines/i24/serial/setup_beamline/setup_zebra_plans.py
- src/mx_bluesky/common/external_interaction/callbacks/common/ispyb_mapping.py
- src/mx_bluesky/common/external_interaction/nexus/nexus_utils.py
- src/mx_bluesky/common/parameters/gridscan.py
- src/mx_bluesky/hyperion/parameters/gridscan.py
- src/mx_bluesky/hyperion/parameters/rotation.py
- tests/test_data/agamemnon/example_collect.json
- tests/unit_tests/beamlines/i24/serial/setup_beamline/test_zebra_plans.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
Fixes #289 
Link to dodal PR: [#1102](https://github.com/DiamondLightSource/dodal/pull/1102)
1. Search repo for `exposure_time` variable
2. Ensure that all occurrences have been renamed to `exposure_time_s`
> (#289) Add units to exposure_time param

- pyproject.toml
- src/mx_bluesky/common/device_setup_plans/xbpm_feedback.py
- src/mx_bluesky/common/preprocessors/preprocessors.py
- src/mx_bluesky/common/protocols/protocols.py
- src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- tests/system_tests/hyperion/experiment_plans/test_fgs_plan.py
- tests/unit_tests/common/device_setup_plans/test_xbpm_feedback.py
- tests/unit_tests/common/preprocessors/test_preprocessors.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_multi_rotation_scan_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
Fixes #891 
Link to dodal PR (if required): (https://github.com/DiamondLightSource/dodal/pull/1099)
1. Confirm undulator preprocessor works
2. Confirm we are using this preprocessor before all data collections, as before
3. Confirm tests pass with the dodal change and that new tests cover everything
> Move undulator check to separate preprocessor

- pyproject.toml
Fixes #908 
Link to dodal PR: #[1110](https://github.com/DiamondLightSource/dodal/pull/1110)
1. Add in a walrus operator inside an assert
2. Check ruff shouts at you with `ruff check`
3. Add in a walrus operator inside an assert in /tests or /system_tests
4. Check ruff **doesn't** shout at you.
> Add RUF018 to lint.select

- src/mx_bluesky/beamlines/aithre_lasershaping/__init__.py
- src/mx_bluesky/beamlines/aithre_lasershaping/check_goniometer_performance.py
- tests/unit_tests/beamlines/aithre_lasershaping/test_check_goniometer_performance.py
Fixes #895
Continuing @co2e14's work (dodal [#910](https://github.com/DiamondLightSource/dodal/pull/910)) 
1. Check the newly added test is passing
> (#895) Add plan for testing goniometer motion

- src/mx_bluesky/beamlines/aithre_lasershaping/__init__.py
- src/mx_bluesky/beamlines/aithre_lasershaping/goniometer_controls.py
- tests/unit_tests/beamlines/aithre_lasershaping/test_goniometer_controls.py
Fixes #930
1. Confirm new test passes
2. Optionally, run plan on goniometer in laser lab
> Plan for changing aithre goniometer omega velocity

- pyproject.toml
- tests/system_tests/hyperion/external_interaction/test_agamemnon.py
See https://github.com/DiamondLightSource/mx-bluesky/pull/949#discussion_r2018649124
1. Confirm agamemnon test passes (`pytest tests/system_tests/hyperion/external_interaction/test_agamemnon.py`)
> Remove specific check on pydantic deprectaion as we have the global one

- src/mx_bluesky/hyperion/external_interaction/callbacks/__main__.py
- tests/unit_tests/hyperion/external_interaction/callbacks/test_external_callbacks.py
Part of #967
1. Confirm new test passes
> Add sleep back in for callback service

- src/mx_bluesky/hyperion/external_interaction/agamemnon.py
- src/mx_bluesky/hyperion/parameters/constants.py
- tests/system_tests/hyperion/external_interaction/test_agamemnon.py
- tests/unit_tests/hyperion/external_interaction/test_agamemnon.py
Fixes #995
Fixes most of the differences except:
* I think GDA is wrong in which parameter version to use
* I need to discuss with @npat113 but I think changing the storage directories might be fine
* I think GDA was wrong about the comments
1. Confirm that, other than the above exceptions, all differences have been addressed
2. Confirm tests (including system tests `pytest tests/system_tests/hyperion/external_interaction/test_agamemnon.py`) pass
> Fix agamemnon differences from testing

- pyproject.toml
- src/mx_bluesky/hyperion/device_setup_plans/manipulate_sample.py
- src/mx_bluesky/hyperion/experiment_plans/change_aperture_then_move_plan.py
- src/mx_bluesky/hyperion/experiment_plans/oav_snapshot_plan.py
- src/mx_bluesky/hyperion/experiment_plans/robot_load_and_change_energy.py
- tests/conftest.py
- tests/unit_tests/hyperion/device_setup_plans/test_manipulate_sample.py
- tests/unit_tests/hyperion/experiment_plans/test_change_aperture_then_move_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_pin_centre_then_xray_centre_plan.py
- tests/unit_tests/hyperion/experiment_plans/test_robot_load_and_change_energy.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
Fixes #1022 
1. Confirm tests pass
> Fix tests against latest dodal

- pyproject.toml
- src/mx_bluesky/common/external_interaction/callbacks/xray_centre/ispyb_callback.py
- src/mx_bluesky/common/plans/common_flyscan_xray_centre_plan.py
- tests/conftest.py
- tests/system_tests/hyperion/external_interaction/callbacks/test_external_callbacks.py
- tests/system_tests/hyperion/external_interaction/test_zocalo_system.py
- tests/unit_tests/common/external_interaction/xray_centre/test_ispyb_callback.py
- tests/unit_tests/common/external_interaction/xray_centre/test_ispyb_handler.py
- tests/unit_tests/common/plans/test_common_flyscan_xray_centre_plan.py
Fixes #1047
Based on https://github.com/DiamondLightSource/mx-bluesky/pull/1046, merge that first
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/1214
1. Confirm tests still pass (including system tests)
> Remove zocalo reading event

- pyproject.toml
- src/mx_bluesky/beamlines/i23/serial.py
- tests/unit_tests/beamlines/i23/test_serial.py
Fixes #1013
Link to dodal PR (if required): [#1220](https://github.com/DiamondLightSource/dodal/pull/1220)
1. Check new test passes
2. Test serial plan on beamline, observe detector move in at start
> I23 Serial Detector Movement

- pyproject.toml
- src/mx_bluesky/beamlines/i04/redis_to_murko_forwarder.py
- src/mx_bluesky/beamlines/i04/thawing_plan.py
Fixes breakage against dodal `main` due to
* DiamondLightSource/dodal#1149
1. Tests pass
> Fix for breakage due to DiamondLightSource/dodal#1149

- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- tests/unit_tests/beamlines/i24/serial/fixed_target/test_ft_collect.py
Fixes #1050
Link to dodal PR (if required): DiamondLightSource/dodal#1226
1. Confirm tests past
> Removed references to collection_time

- pyproject.toml
- src/mx_bluesky/hyperion/utils/validation.py
- tests/conftest.py
- tests/system_tests/conftest.py
- tests/unit_tests/beamlines/i04/test_thawing.py
- tests/unit_tests/common/experiment_plans/test_grid_detection_plan.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/892
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/1108
1. Confirm tests pass
> Fix tests for reading beam centre from OAV

- pyproject.toml
- src/mx_bluesky/common/external_interaction/nexus/nexus_utils.py
- src/mx_bluesky/hyperion/utils/validation.py
- tests/system_tests/hyperion/external_interaction/test_nexgen.py
- tests/unit_tests/hyperion/external_interaction/nexus/test_compare_nexus_to_gda_exhaustively.py
- tests/unit_tests/hyperion/external_interaction/test_write_rotation_nexus.py
Fixes tests against new `nexgen` version
1. Reinstall your environment `./utility_scripts/dls_dev_env.sh`
2. Confirm all tests pass
> Fixed for new nexgen version

- src/mx_bluesky/beamlines/i24/serial/fixed_target/FT-gui-edm/pumpprobe-py3v1.edl
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
- src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
- tests/unit_tests/beamlines/i24/serial/fixed_target/test_chip_manager.py
- tests/unit_tests/beamlines/i24/serial/fixed_target/test_ft_collect.py
> I24 serial: fix checker pattern value

- docs/developer/general/how-to/create-a-release.rst
Adds an extra bullet point to the release docs
> Minor addition to release docs

- src/mx_bluesky/hyperion/experiment_plans/rotation_scan_plan.py
- src/mx_bluesky/hyperion/external_interaction/agamemnon.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/snapshot_callback.py
- src/mx_bluesky/hyperion/parameters/constants.py
- src/mx_bluesky/hyperion/parameters/load_centre_collect.py
- tests/system_tests/hyperion/external_interaction/test_agamemnon.py
- tests/test_data/parameter_json_files/good_test_load_centre_collect_params.json
- tests/unit_tests/common/external_interaction/callbacks/common/test_snapshot_callback.py
- tests/unit_tests/hyperion/experiment_plans/test_rotation_scan_plan.py
- tests/unit_tests/hyperion/parameters/test_parameter_model.py
Fixes various issues arising from
* #1118
* Wasn't using GPU results as we need to set `use_gpu` on the Zocalo device
* Grid snapshots worked but still moved the backlight in
* We should set `use_grid_snapshots` for multipin by default
* Snapshot folder needs to be created
Link to dodal PR (if required):
* DiamondLightSource/dodal#1311
1. Do thing x
> Beamline fixes from v1.5.0 testing

- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
Fixes broken a system test in `test_load_centre_collect_full_plan` due to a change in the robot load callback implementation in 
* #1078 
1. Do thing x
> Fix broken system tests due to missing parameter in robot load callback assert

- tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
Fixes system test broken by 
* #1078
1. System tests pass
> Fix broken system test expeye assertion

- .github/workflows/_container.yml
- helmcharts/hyperion/values.yaml
- utility_scripts/deploy/deploy_mx_bluesky_app_to_k8s.sh
Fixes #1155
Also fixes the debug log folder being the same as non-k8s hyperion and also tweaks to the deployment script.
1. Do thing x
> Fix issue where Hyperion and MX-Bluesky container images were the same image

- tests/system_tests/hyperion/external_interaction/test_baton_handler_soak.py
Fixes system test failures in `test_baton_handler_soak.py`
Link to dodal PR (if required): N/A
1. System tests pass - https://gitlab.diamond.ac.uk/MX-GDA/hyperion-system-testing/-/pipelines/88833
> Fix broken baton_handler soak system tests

- docs/developer/general/how-to/deploy-a-release.rst
- docs/developer/hyperion/index.rst
- docs/developer/hyperion/reference/readme.md
- docs/user/hyperion/configuration.rst
- docs/user/hyperion/index.rst
- docs/user/hyperion/running.rst
- run_hyperion.sh
- utility_scripts/request_baton.sh
Implements changes to Hyperion launcher from previous testing #1188 
1. Do thing x
> Hyperion udc launcher changes from testing

- src/mx_bluesky/common/external_interaction/callbacks/common/ispyb_callback_base.py
- src/mx_bluesky/common/external_interaction/callbacks/common/plan_reactive_callback.py
- src/mx_bluesky/common/external_interaction/callbacks/xray_centre/ispyb_callback.py
- src/mx_bluesky/common/external_interaction/callbacks/xray_centre/nexus_callback.py
- src/mx_bluesky/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
- tests/unit_tests/common/external_interaction/xray_centre/test_ispyb_callback.py
Fixes #1241 
Link to dodal PR (if required): #XXX
1. Search all instances of "recieve", "recieved" and "recieving" in vscode 
2. Check that no instances show up
> Fixed spelling of receive

- pyproject.toml
- tests/conftest.py
- tests/unit_tests/beamlines/aithre_lasershaping/test_goniometer_controls.py
- tests/unit_tests/beamlines/i04/test_thawing.py
- tests/unit_tests/beamlines/i23/test_serial.py
- tests/unit_tests/beamlines/i24/serial/conftest.py
- tests/unit_tests/common/experiment_plans/inner_plans/test_udc_default_state.py
Updates mx-bluesky to match changes made in dodal.
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/1513 
1. Confirm tests pass
> Fix motor patch location

- tests/unit_tests/beamlines/i04/test_redis_to_murko_forwarder.py
Fixes `redis_to_murko_forwarder` unit test in line with dodal changes to `MurkoResult`
1. Tests pass
> Fix unit tests for redis-to-murko in line with MurkoResult changes
